### ISSUE TITLE
node-lightning project logo

### ISSUE THREAD

**Issue by bmancini55** [altangent/node-lightning#145]
A logo would be pretttty awesome :zap: 

While beggars shouldn't be choosers, I've been thinking a play on the Node.js/JS hexagon with a lightning in blue would look pretty awesome.

Upload that sucker to an assets folder in the project.  Add a thanks to yourself in the README.md and you'll be a project hero.

**Comment by outofgamut** [comment]
i can help with this

**Comment by bmancini55** [comment]
Awesome! I look forward to the help
