### ISSUE TITLE
bitcoin: unable to parse Tx with no inputs and 1 output

### ISSUE THREAD

**Issue by matthewjablack** [altangent/node-lightning#167]
Currently, the Tx class in @node-dlc/bitcoin is unable to parse a base transaction with no inputs and 1 output.

This is because zero inputs and 1 output is serialized as "0001", which also happens to be the witness marker and version flag. However, these are invalid witness transactions because a Tx needs to have a witness to be considered a witness transaction.

Example tx: `02000000000100e1f5050000000017a9148fe46e05e329badba1c390a5ea2c0ad7de2059cd8700000000`

There is support for parsing this type of transaction in Bitcoin Core and Bitcoin-s (perhaps others, I haven't checked). 

[Bitcoin-s](https://github.com/bitcoin-s/bitcoin-s) currently implements a [throw catch](https://github.com/bitcoin-s/bitcoin-s/blob/master/core/src/main/scala/org/bitcoins/core/protocol/transaction/Transaction.scala#L115) to solve this issue. They also have a [test](https://github.com/bitcoin-s/bitcoin-s/blob/01d89df1b7c6bc4b1594406d54d5e6019705c654/core-test/src/test/scala/org/bitcoins/core/protocol/transaction/TransactionTest.scala#L88) for ensuring their Transaction module is able to parse these types of transactions.

I suggest adding a throw/catch to [Tx.parse](https://github.com/altangent/node-lightning/blob/main/packages/bitcoin/lib/Tx.ts#L28) and adding a [test](https://github.com/altangent/node-lightning/blob/main/packages/bitcoin/__tests__/Tx.spec.ts) for this type of transaction.

**Comment by bmancini55** [comment]
@matthewjablack, thanks for submitting the issue! Shouldn't be too much of a problem to fix this.  I'll take a look over the weekend here and try to get a patch applied along with the appropriate vectors.  

I have a standing issue #158 to pull in the vectors used in Bitcoin core. That likely would have found this!  Best intentions I guess haha
