### ISSUE TITLE
bitcoind: incorrect type for BlockSummary tx

### ISSUE THREAD

**Issue by matthewjablack** [altangent/node-lightning#172]
Currently `BlockSummary` type specifies tx as `tx: [string]`. If the intention was to only have the coinbase transaction, `string` would make more sense. Otherwise `string[]` makes more sense. 

https://github.com/altangent/node-lightning/blob/main/packages/bitcoind/lib/types/blocksummary.ts#L10

**Comment by bmancini55** [comment]
@matthewjablack thanks for catching this!  Fixed and released in v0.22.1.
