### ISSUE TITLE
wire: create `closing_signed` message type

### ISSUE THREAD

**Issue by bmancini55** [altangent/node-lightning#180]
In the wire project, create the `closing_signed` message type. 

- This type should include properties as defined in [BOLT #2]( https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#closing-negotiation-closing_signed).  
- It should implement `IWireMessage` and `deserialize` and `serialize` methods.  
- It should include basic unit tests for these methods

**Comment by Vib-UX** [comment]
[BOLT #2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#closing-negotiation-closing_signed) 

- Parameters are defined according to `closing_signed` in [BOLT #2](https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#closing-negotiation-closing_signed) 
- Implementation is as per the standards given 
- UT attached for testing
[PR #180 (Closing_Signed).zip](https://github.com/altangent/node-lightning/files/6851087/PR.180.Closing_Signed.zip)

**Comment by bmancini55** [comment]
Closed with #182
