### ISSUE TITLE
Yarn dependency installation fails inside Docker container

### ISSUE THREAD

**Issue by steliosrammos** [altangent/node-lightning#260]
Hey there, trying to use this library as a a dependency on a project running within a Docker container and getting the following error during the `yarn install` phase: 

```
error /usr/app/node_modules/@node-lightning/secp256k1: Command failed.
Exit code: 128
Command: git submodule update --init
Arguments: 
Directory: /usr/app/node_modules/@node-lightning/secp256k1
Output:
fatal: not a git repository (or any of the parent directories): .git
```

## Environment

Node version: 18.12.0

### Base Dockerfile
```
ARG NODE_VERSION=18.12.0
FROM --platform=linux/amd64 node:${NODE_VERSION}-alpine AS base

RUN apk update && apk add git
```

**Comment by bmancini55** [comment]
You'll need to create a git repo `git init` inside your container where the project code is. This is necessary (for now), because it loads libsecp256k1 as a git submodule instead of using a pre-built version of it.  

I need to work on prebuilds for that module that step isn't necessary.

**Comment by bmancini55** [comment]
This should be resolve in v0.28.0, the git prebuild dependency was removed.  I will close the issue for now, but feel free reopen if there is still an issue.
